[package]
name = "vaseline-healthy-white-server"
version = "0.1.0"
authors = ["Jacky Boen <jacky.boen@bartleboglehegarty.com"]

[dependencies]
iron = "*"
mount = "*"
persistent = "*"
router = "*"
staticfile = "*"
urlencoded = "*"
rustc-serialize = "*"
